Host:
  127.0.0.1
Port:
  8008
MySql:
  DataSource:
	your_db address
Redis:
  Addr:
    192.168.195.135:1003
  Pwd:
    Lh201807.
  DB:
    0
BaseKey:
  UserKey:
    "user:cache:"
JWT:
  Secret:
    "you_secret"